name: cvms_mobile
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  #firebase auth
  firebase_auth: ^6.0.2
  #firestore
  cloud_firestore: ^6.0.1
  #firebase core
  firebase_core: ^4.1.0
  #equatable
  equatable: ^2.0.7
  #state management
  flutter_bloc: ^9.1.1
  bloc: ^9.0.0
  #for qr scanner
  mobile_scanner: ^7.0.1
  #chart
  syncfusion_flutter_charts: ^31.1.19
  #google fonts package
  google_fonts: ^6.3.1
  #icon package
  phosphor_flutter: ^2.1.0
  #audio player
  audioplayers: ^6.5.1
  #shared pref
  shared_preferences: ^2.5.3
  #rx
  rxdart: ^0.28.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
    - assets/icons/
    - assets/sounds/

  fonts:
    - family: Sora
      fonts:
        - asset: assets/fonts/Sora-Light.ttf
          weight: 300
        - asset: assets/fonts/Sora-Regular.ttf
          weight: 400
        - asset: assets/fonts/Sora-Medium.ttf
          weight: 500
        - asset: assets/fonts/Sora-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Sora-Bold.ttf
          weight: 700
        - asset: assets/fonts/Sora-ExtraBold.ttf
          weight: 800
